name: infininotes
description: A Google Keep-like notes app built with Flutter and Node.js
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.6.0
  shared_preferences: ^2.5.5
  google_sign_in: 6.2.1
  flutter_secure_storage: ^10.3.0
  intl: ^0.20.2
  uuid: ^4.5.3
  flutter_colorpicker: ^1.1.0
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon_1024.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon_1024.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1A73E8"
  adaptive_icon_foreground: "assets/icon_1024.png"